### ISSUE TITLE
The database file cannot be found

### ISSUE THREAD

**Issue by jayo2005** [eppsteve/GymManagerPro#3]
I get the following. The database file cannot be found. Check the path to the database. [ Data Source = C:\Users\TOM\AppData\Local\Apps\2.0\Data\K1ZPTRWY.Q5G\LYQ8DX2T.CX5\gymm..tion_0000000000000000_0000.0001_5d17ea6c3efb3df7\Data....\Database.sdf ]

**Comment by eppsteve** [comment]
try the following
Select the Database.sdf and Press the (F4) key
Set property "Copy to Output Directory" as 'Copy if Newer'.
